// ⚠️  AUTO-GENERATED — do not edit manually.
// Generated by scripts/generate-env.js from environment variables.

export const environment = {
  production: true,
  appVersion: '0.0.0',

  // API Configuration
  api: {
    baseUrl: 'http://localhost:8080/api',
    timeout: 30,
    retryAttempts: 1
  },

  // Authentication Configuration
  auth: {
    tokenKey: 'cineq_token',
    userKey: 'cineq_user',
    tokenExpiry: 2
  },

  // App Configuration
  app: {
    name: 'CineQ',
    defaultRoute: '/',
    loginRoute: '/'
  },

  // Feature Flags
  features: {
    enableGoogleAuth: false,
    enableRegistration: true,
    enableRememberMe: true,
    enableForgotPassword: true
  }
};
