// ⚠️  AUTO-GENERATED — do not edit manually.
// Generated by scripts/generate-env.js from environment variables.

export const environment = {
  production: true,
  appVersion: '0.0.0',

  // API Configuration
  api: {
    baseUrl: 'http://localhost:8080/api',
    timeout: 30,
    retryAttempts: 1
  },

  // Authentication Configuration
  // Token is now stored in HttpOnly cookie - only user data cached locally
  auth: {
    userKey: 'cineq_user',
    tokenExpiry: 2
  },

  // App Configuration
  app: {
    name: 'CineQ',
    defaultRoute: '/',
    loginRoute: '/'
  },

  // Feature Flags
  features: {
    enableGoogleAuth: false,
    enableRegistration: true,
    enableRememberMe: true,
    enableForgotPassword: true
  },
  googleClientId : '819220598893-hsj45m1ffsv3q9onjuaq1g031k489m2s.apps.googleusercontent.com'
};
