/**
 * Script to generate environment.prod.ts from environment variables.
 * This prevents committing sensitive data to GitHub.
 *
 * Usage:
 *   node scripts/generate-env.js
 *
 *
 */

const fs = require('fs');
const path = require('path');

// Read package.json for version
const packageJson = require('../package.json');

// ──────────────────────────── Environment Variables ────────────────────────────

const env = {
  // API Configuration
  API_BASE_URL: process.env.API_BASE_URL || 'http://localhost:8080/api',
  API_TIMEOUT: process.env.API_TIMEOUT || '30',
  API_RETRY_ATTEMPTS: process.env.API_RETRY_ATTEMPTS || '1',

  // Auth Configuration
  AUTH_TOKEN_KEY: process.env.AUTH_TOKEN_KEY || 'cineq_token',
  AUTH_USER_KEY: process.env.AUTH_USER_KEY || 'cineq_user',
  AUTH_TOKEN_EXPIRY: process.env.AUTH_TOKEN_EXPIRY || '2', // hours

  // App Configuration
  APP_NAME: process.env.APP_NAME || 'CineQ',
  APP_DEFAULT_ROUTE: process.env.APP_DEFAULT_ROUTE || '/',
  APP_LOGIN_ROUTE: process.env.APP_LOGIN_ROUTE || '/',

  // Feature Flags
  FEATURE_ENABLE_GOOGLE_AUTH: process.env.FEATURE_ENABLE_GOOGLE_AUTH || 'false',
  FEATURE_ENABLE_REGISTRATION: process.env.FEATURE_ENABLE_REGISTRATION || 'true',
  FEATURE_ENABLE_REMEMBER_ME: process.env.FEATURE_ENABLE_REMEMBER_ME || 'true',
  FEATURE_ENABLE_FORGOT_PASSWORD: process.env.FEATURE_ENABLE_FORGOT_PASSWORD || 'true',
};

// ──────────────────────────── Template ────────────────────────────

const environmentContent = `// ⚠️  AUTO-GENERATED — do not edit manually.
// Generated by scripts/generate-env.js from environment variables.

export const environment = {
  production: true,
  appVersion: '${packageJson.version}',

  // API Configuration
  api: {
    baseUrl: '${env.API_BASE_URL}',
    timeout: ${parseInt(env.API_TIMEOUT, 10)},
    retryAttempts: ${parseInt(env.API_RETRY_ATTEMPTS, 10)}
  },

  // Authentication Configuration
  auth: {
    tokenKey: '${env.AUTH_TOKEN_KEY}',
    userKey: '${env.AUTH_USER_KEY}',
    tokenExpiry: ${parseInt(env.AUTH_TOKEN_EXPIRY, 10)}
  },

  // App Configuration
  app: {
    name: '${env.APP_NAME}',
    defaultRoute: '${env.APP_DEFAULT_ROUTE}',
    loginRoute: '${env.APP_LOGIN_ROUTE}'
  },

  // Feature Flags
  features: {
    enableGoogleAuth: ${env.FEATURE_ENABLE_GOOGLE_AUTH === 'true'},
    enableRegistration: ${env.FEATURE_ENABLE_REGISTRATION === 'true'},
    enableRememberMe: ${env.FEATURE_ENABLE_REMEMBER_ME === 'true'},
    enableForgotPassword: ${env.FEATURE_ENABLE_FORGOT_PASSWORD === 'true'}
  }
};
`;

// ──────────────────────────── Write File ────────────────────────────

const envFilePath = path.join(__dirname, '../src/environments/environment.prod.ts');
fs.writeFileSync(envFilePath, environmentContent, 'utf8');

console.log('✅ Generated environment.prod.ts from environment variables');
console.log('📝 File written to:', envFilePath);

// Log which env vars were used (without exposing sensitive values)
console.log('\\n📋 Environment variables status:');
console.log('  API_BASE_URL:', process.env.API_BASE_URL ? '✓ Set' : '✗ Using default');
console.log('  AUTH_TOKEN_KEY:', process.env.AUTH_TOKEN_KEY ? '✓ Set' : '✗ Using default');
console.log('  APP_NAME:', process.env.APP_NAME ? '✓ Set' : '✗ Using default');
console.log('  FEATURE_ENABLE_GOOGLE_AUTH:', env.FEATURE_ENABLE_GOOGLE_AUTH);
console.log('  FEATURE_ENABLE_REGISTRATION:', env.FEATURE_ENABLE_REGISTRATION);
